######################################################################
#
# File name : binToBCD_compile.do
# Created on: Thu Nov 22 20:47:56 +0100 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/work
F:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim

F:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xil_defaultlib

F:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work xil_defaultlib  \
"../../../../fullAdderSegment.srcs/sources_1/imports/new/fullAdder.vhd" \
"../../../../fullAdderSegment.srcs/sources_1/imports/new/fourBitFullAdder.vhd" \
"../../../../fullAdderSegment.srcs/sources_1/new/binToBCD.vhd" \
"../../../../fullAdderSegment.srcs/sources_1/new/fourBitAdderTop.vhd" \
"../../../../fullAdderSegment.srcs/sources_1/new/bcdToSeg.vhd" \
"../../../../fullAdderSegment.srcs/sources_1/new/segmentMux.vhd" \
"../../../../fullAdderSegment.srcs/sim_1/new/binToBVD_Tb.vhd" \
"../../../../fullAdderSegment.srcs/sim_1/new/fourBitAdderTop_Tb.vhd" \
"../../../../fullAdderSegment.srcs/sim_1/new/bcdToSeg_Tb.vhd" \
"../../../../fullAdderSegment.srcs/sim_1/new/segmentMux_Tb.vhd" \


quit -force

