# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath F:/Modeltech_pe_edu_10.4a/win32pe_edu
set_param xicom.use_bs_reader 1
set_param synth.incrementalSynthesisCache {C:/Users/Dion Legierse/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12148-DESKTOP-24KCCOQ/incrSyn}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/programmeerbareHardware1/fullAdderSegment/fullAdderSegment.cache/wt [current_project]
set_property parent.project_path F:/programmeerbareHardware1/fullAdderSegment/fullAdderSegment.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo f:/programmeerbareHardware1/fullAdderSegment/fullAdderSegment.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  F:/programmeerbareHardware1/fullAdderSegment/fullAdderSegment.srcs/sources_1/imports/new/fullAdder.vhd
  F:/programmeerbareHardware1/fullAdderSegment/fullAdderSegment.srcs/sources_1/imports/new/fourBitFullAdder.vhd
  F:/programmeerbareHardware1/fullAdderSegment/fullAdderSegment.srcs/sources_1/new/binToBCD.vhd
  F:/programmeerbareHardware1/fullAdderSegment/fullAdderSegment.srcs/sources_1/new/fourBitAdderTop.vhd
  F:/programmeerbareHardware1/fullAdderSegment/fullAdderSegment.srcs/sources_1/new/bcdToSeg.vhd
  F:/programmeerbareHardware1/fullAdderSegment/fullAdderSegment.srcs/sources_1/new/segmentMux.vhd
  F:/programmeerbareHardware1/fullAdderSegment/fullAdderSegment.srcs/sources_1/new/clock_divider.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/programmeerbareHardware1/fullAdderSegment/fullAdderSegment.srcs/constrs_1/new/basys3.xdc
set_property used_in_implementation false [get_files F:/programmeerbareHardware1/fullAdderSegment/fullAdderSegment.srcs/constrs_1/new/basys3.xdc]


synth_design -top fourBitAdderTop -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fourBitAdderTop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fourBitAdderTop_utilization_synth.rpt -pb fourBitAdderTop_utilization_synth.pb"
